Repository MetaPolyChat/PolyChat-BE, pull requests merged in 2024-09, with the labels that each got.

#17 업적 목록 엔티티 추가
  src/main/java/com/polychat/polychatbe/achievement/command/application/service/AchievementService.java
  src/main/java/com/polychat/polychatbe/achievement/command/domain/aggregate/Achievement.java
  src/main/java/com/polychat/polychatbe/achievement/command/domain/repository/AchievementRepository.java
  src/main/java/com/polychat/polychatbe/achievement/command/domain/service/AchievementDomainService.java
  src/main/java/com/polychat/polychatbe/achievement/command/infrastructure/FireBaseImageUploadService.java
  src/main/java/com/polychat/polychatbe/achievement/query/dto/AchievementResponseDTO.java
  src/main/java/com/polychat/polychatbe/achievement/query/repository/AchievementSearchRepository.java
  src/main/java/com/polychat/polychatbe/achievement/query/service/AchievementSearchService.java
  src/main/java/com/polychat/polychatbe/achivement/.gitkeep
  src/main/resources/mapper/.gitkeep
  src/main/resources/mappers/AchievementMapper.xml
Labels: feature

#21 Feature/20 refactor friend domain
  src/main/java/com/polychat/polychatbe/achievement/command/application/controller/AchievementController.java
  src/main/java/com/polychat/polychatbe/achievement/command/application/dto/AchievementRequest.java
  src/main/java/com/polychat/polychatbe/achievement/command/application/service/AchievementService.java
  src/main/java/com/polychat/polychatbe/achievement/command/domain/aggregate/Achievement.java
  src/main/java/com/polychat/polychatbe/achievement/command/domain/service/AchievementDomainService.java
  src/main/java/com/polychat/polychatbe/achievement/query/controller/AchievementSearchController.java
  src/main/java/com/polychat/polychatbe/friend/command/application/service/FriendApplicationService.java
  src/main/java/com/polychat/polychatbe/friend/command/domain/service/FriendRequestAcceptService.java
  src/main/java/com/polychat/polychatbe/friend/query/dto/FriendResponseDTO.java
  src/main/java/com/polychat/polychatbe/friend/query/dto/FriendUserInfoDTO.java
  src/main/java/com/polychat/polychatbe/friend/query/dto/OneUserFriendResponseDTO.java
  src/main/java/com/polychat/polychatbe/friend/query/repository/FriendMyBatisRepository.java
  src/main/java/com/polychat/polychatbe/friend/query/repository/FriendSearchRepository.java
  src/main/java/com/polychat/polychatbe/friend/query/service/FriendSearchService.java
  src/main/java/com/polychat/polychatbe/friendRequest/command/domain/model/FriendRequest.java
  src/main/resources/mappers/FriendMapper.xml
  src/test/java/com/polychat/polychatbe/achievement/command/domain/AchievementTest.java
  src/test/java/com/polychat/polychatbe/friend/command/domain/FriendTest.java
Labels: refactor

#24 image uploader 인터페이스 추가
  src/main/java/com/polychat/polychatbe/achievement/command/domain/service/ImageUploadService.java
  src/main/resources/mappers/FriendMapper.xml
Labels: refactor

#28 rest api 응답코드 작성, mapper 위치 수정
  build.gradle
  src/main/java/com/polychat/polychatbe/achievement/command/application/controller/AchievementController.java
  src/main/java/com/polychat/polychatbe/announcement/command/application/controller/AnnounceController.java
  src/main/java/com/polychat/polychatbe/announcement/query/controller/AnnouncementSearchController.java
  src/main/java/com/polychat/polychatbe/config/SwaggerConfig.java
  src/main/java/com/polychat/polychatbe/friend/command/application/controller/FriendController.java
  src/main/java/com/polychat/polychatbe/friend/query/controller/FriendSearchController.java
  src/main/java/com/polychat/polychatbe/friendRequest/command/application/controller/FriendRequestController.java
  src/main/java/com/polychat/polychatbe/friendRequest/command/application/service/FriendRequestApplicationService.java
  src/main/resources/mappers/AnnouncementMapper.xml
Labels: refactor

#27 #26 swagger api 추가
  build.gradle
  src/main/java/com/polychat/polychatbe/achievement/command/application/controller/AchievementController.java
  src/main/java/com/polychat/polychatbe/announcement/command/application/controller/AnnounceController.java
  src/main/java/com/polychat/polychatbe/announcement/query/controller/AnnouncementSearchController.java
  src/main/java/com/polychat/polychatbe/config/SwaggerConfig.java
  src/main/java/com/polychat/polychatbe/friend/command/application/controller/FriendController.java
  src/main/java/com/polychat/polychatbe/friend/query/controller/FriendSearchController.java
  src/main/java/com/polychat/polychatbe/friendRequest/command/application/controller/FriendRequestController.java
  src/main/java/com/polychat/polychatbe/friendRequest/command/application/service/FriendRequestApplicationService.java
Labels: documentation

#34 #33 swagger 문서 작성
  src/main/java/com/polychat/polychatbe/achievement/command/application/controller/AchievementController.java
  src/main/java/com/polychat/polychatbe/achievement/command/application/dto/AchievementRequest.java
  src/main/java/com/polychat/polychatbe/announcement/.gitkeep
  src/main/java/com/polychat/polychatbe/announcement/command/application/controller/AnnounceController.java
  src/main/java/com/polychat/polychatbe/announcement/command/application/dto/AnnounceAddRequest.java
  src/main/java/com/polychat/polychatbe/announcement/query/controller/AnnouncementSearchController.java
  src/main/java/com/polychat/polychatbe/friend/command/application/controller/FriendController.java
  src/main/java/com/polychat/polychatbe/friend/command/application/dto/FriendUserDTO.java
  src/main/java/com/polychat/polychatbe/friendRequest/command/application/dto/FriendRequestDTO.java
  src/main/java/com/polychat/polychatbe/friendRequest/command/application/dto/FriendRequestStatusDTO.java
Labels: documentation

#40 fixed #5 apply CQRS & add swagger & finish Controller test
  build.gradle
  src/main/java/com/polychat/polychatbe/interest/command/domain/model/Interest.java
  src/main/java/com/polychat/polychatbe/interest/command/domain/repository/InterestRepository.java
  src/main/java/com/polychat/polychatbe/interest/command/domain/service/InterestService.java
  src/main/java/com/polychat/polychatbe/interest/query/controller/.gitkeep
  src/main/java/com/polychat/polychatbe/interest/query/controller/InterestFindController.java
  src/main/java/com/polychat/polychatbe/interest/query/repository/InterestMapper.java
  src/main/java/com/polychat/polychatbe/interest/query/repository/UserInterestMapper.java
  src/main/java/com/polychat/polychatbe/interest/query/service/.gitkeep
  src/main/java/com/polychat/polychatbe/interest/query/service/InterestFindService.java
  src/main/resources/application.yml
  src/main/resources/mappers/InterestMapper.xml
  src/main/resources/mappers/UserInterestMapper.xml
Labels: feature, Aggregate

#47 Feature/user achievement
  src/main/java/com/polychat/polychatbe/achievement/query/dto/AchievementResponseDTO.java
  src/main/java/com/polychat/polychatbe/userAchievement/command/application/controller/UserAchievementController.java
  src/main/java/com/polychat/polychatbe/userAchievement/command/application/dto/UserAchievementModifyDTO.java
  src/main/java/com/polychat/polychatbe/userAchievement/command/application/dto/UserAchievementRegistDTO.java
  src/main/java/com/polychat/polychatbe/userAchievement/command/application/service/UserAchievementService.java
  src/main/java/com/polychat/polychatbe/userAchievement/command/domain/aggregate/UserAchievement.java
  src/main/java/com/polychat/polychatbe/userAchievement/command/domain/repository/UserAchievementRepository.java
  src/main/java/com/polychat/polychatbe/userAchievement/query/controller/UserAchievementSearchController.java
  src/main/java/com/polychat/polychatbe/userAchievement/query/dto/OneUserAchievementDTO.java
  src/main/java/com/polychat/polychatbe/userAchievement/query/dto/UserAchievementResponseDTO.java
  src/main/java/com/polychat/polychatbe/userAchievement/query/repository/UserAchievementSearchRepository.java
  src/main/java/com/polychat/polychatbe/userAchievement/query/service/UserAchievementSearchService.java
  src/main/resources/mappers/UserAchievementMapper.xml
  src/test/java/com/polychat/polychatbe/achievement/command/domain/AchievementTest.java
  src/test/java/com/polychat/polychatbe/announcement/application/AnnouncementTest.java
  src/test/java/com/polychat/polychatbe/friendRequest/command/domain/FriendRequestTest.java
  src/test/java/com/polychat/polychatbe/userAchievement/command/application/service/UserAchievementTest.java
Labels: feature

#50 관리자 페이지 공지사항 관리 기능 추가중
  src/main/admin-page/src/AxiosRequest/Axios.ts
  src/main/admin-page/src/Component/Annoucement.tsx
  src/main/admin-page/src/Component/AnnouncementAdd.tsx
  src/main/admin-page/src/Component/Layout.tsx
  src/main/admin-page/src/Routers.tsx
  src/main/java/com/polychat/polychatbe/announcement/command/application/controller/AnnouncementController.java
  src/main/java/com/polychat/polychatbe/announcement/query/controller/AnnouncementSearchController.java
Labels: feature

#57 Feature/admin page react
  src/main/admin-page/package-lock.json
  src/main/admin-page/package.json
  src/main/admin-page/src/Component/BlockUser.tsx
  src/main/admin-page/src/Component/HomePage.tsx
  src/main/admin-page/src/Component/Sidebar.tsx
  src/main/admin-page/src/Routers.tsx
Labels: feature
